apiVersion: v1
data:
  amf.yaml: |
    logger:
      file: /var/log/open5gs/amf.log

    global:
      max:
        ue: 1024  # The number of UE can be increased depending on memory size.

    amf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 8080
        client:
          scp:
            - uri: http://{{ .Values.prefix }}-scp:8080
      ngap:
        server:
          - address: 0.0.0.0
      metrics:
        server:
          - address: 0.0.0.0
            port: 9090
      guami:
        - plmn_id:
            mcc: {{ .Values.mcc }}
            mnc: {{ .Values.mnc }}
          amf_id:
            region: 2
            set: 1
      tai:
        - plmn_id:
            mcc: {{ .Values.mcc }}
            mnc: {{ .Values.mnc }}
          tac: {{ .Values.tac }}      
        
      plmn_support:
        - plmn_id:
            mcc: {{ .Values.mcc }}
            mnc: {{ .Values.mnc }}
          s_nssai:
            - sst: 1

      security:
        integrity_order : [ NIA2, NIA1, NIA0 ]
        ciphering_order : [ NEA0, NEA1, NEA2 ]
      network_name:
        full: Open5GS
        short: Next
      amf_name: {{ .Values.prefix }}-amf0
      time:
        t3512:
          value: 540    # 9 minutes * 60 = 540 seconds
kind: ConfigMap
metadata:
  name: {{ .Values.prefix }}-amf