apiVersion: v1
data:
  ausf.yaml: |
    logger:
      file: /var/log/open5gs/ausf.log

    global:
      max:
        ue: 1024  # The number of UE can be increased depending on memory size.

    ausf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 8080
        client:
          scp:
            - uri: http://{{ .Values.prefix }}-scp:8080

kind: ConfigMap
metadata:
  name: {{ .Values.prefix }}-ausf    
