apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prefix }}-ausf
  labels:
    app: {{ .Values.prefix }}-ausf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.prefix }}-ausf
  template:
    metadata:
      labels:
        app: {{ .Values.prefix }}-ausf
      annotations:
        sidecar.istio.io/inject: "{{ .Values.istio_enabled }}"        
    spec:
      securityContext:
        runAsUser: 1024
        runAsGroup: 1024
        fsGroup: 1024    
      imagePullSecrets:
      - name: {{ .Values.registry_secret }} 
      initContainers:
      - name: wait-scp
        image: {{ .Values.registry_url }}/{{ .Values.init_image_name }}:{{ .Values.image_tag }}  
        command:
           - "/opt/wait_scp.sh" 
        env: 
          - name: PREFIX
            value: {{ .Values.prefix }}                   
      containers:
      - name: {{ .Values.prefix }}-ausf
        image: {{ .Values.registry_url }}/{{ .Values.open5gs_image_name }}:{{ .Values.image_tag }}
        env:
          - name: NETYPE
            value: ausf  
          - name: PREFIX
            value: {{ .Values.prefix }}               
        command:
           - "/opt/start_app.sh"
        volumeMounts:
            - name: {{ .Values.prefix }}
              mountPath: /opt/open5gs/config/

        ports:
        - containerPort: 8080 
      volumes:
        - name: {{ .Values.prefix }}
          configMap:
            name: {{ .Values.prefix }}-ausf
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.prefix }}-ausf
  name: {{ .Values.prefix }}-ausf
spec:
  ports:
  - port: 8080
    name: http2
    protocol: TCP
    targetPort: 8080  
  selector:
    app: {{ .Values.prefix }}-ausf
  sessionAffinity: None
  type: ClusterIP            

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.prefix }}-ausf-gw
spec:
  selector:
    istio: ingressgateway 
  servers:
  - port:
      number: 80
      name: http2
      protocol: HTTP2
    hosts:
    - ausf.{{ .Values.istio_domain }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.prefix }}-ausf-vs
spec:
  hosts:
  - ausf.{{ .Values.istio_domain }}
  gateways:
  - {{ .Values.prefix }}-ausf-gw
  http:
  - match:
    - uri:
        prefix: /  
    route:
    - destination:
        host: {{ .Values.prefix }}-ausf
        port:
          number: 8080        