apiVersion: v1
data:
  ausf.yaml: |
    logger:
        file: /var/log/open5gs/ausf.log
    sbi:
        server:
          no_tls: true
          cacert: /etc/open5gs/tls/ca.crt
          key: /etc/open5gs/tls/ausf.key
          cert: /etc/open5gs/tls/ausf.crt
        client:
          no_tls: true
          cacert: /etc/open5gs/tls/ca.crt
          key: /etc/open5gs/tls/ausf.key
          cert: /etc/open5gs/tls/ausf.crt
    ausf:
        sbi:
          - addr: 0.0.0.0
            port: 8080
    scp:
        sbi:
          - addr: {{ .Values.prefix }}-scp
            port: 8080
    parameter:
    max:
    time:
kind: ConfigMap
metadata:
  name: {{ .Values.prefix }}-ausf    
