apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prefix }}-bsf
  labels:
    app: {{ .Values.prefix }}-bsf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.prefix }}-bsf
  template:
    metadata:
      labels:
        app: {{ .Values.prefix }}-bsf
    spec:
      securityContext:
        runAsUser: 1024
        runAsGroup: 1024
        fsGroup: 1024    
      imagePullSecrets:
      - name: {{ .Values.registry_secret }}
      initContainers:
      - name: wait-scp
        image: {{ .Values.registry_url }}/{{ .Values.init_image_name }}:{{ .Values.image_tag }}  
        command:
           - "/opt/wait_scp.sh"  
        env: 
          - name: PREFIX
            value: {{ .Values.prefix }}             
      containers:
      - name: {{ .Values.prefix }}-smf
        image: {{ .Values.registry_url }}/{{ .Values.open5gs_image_name }}:{{ .Values.image_tag }}  
        env:
          - name: NETYPE
            value: bsf 
          - name: PREFIX
            value: {{ .Values.prefix }}               
        command:
           - "/opt/start_app.sh"
        volumeMounts:
            - name: open5gs
              mountPath: /opt/open5gs/config/
            - name: open5gs-hnet
              mountPath: /etc/open5gs/hnet

        ports:
        - containerPort: 8080
      volumes:
        - name: {{ .Values.prefix }}
          configMap:
            name: {{ .Values.prefix }}-bsf
        - name: {{ .Values.prefix }}-hnet
          secret:
            secretName: hnet
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.prefix }}-bsf
  name: {{ .Values.prefix }}-bsf
spec:
  ports:
  - port: 8080
    name: http2
    protocol: TCP
    targetPort: 8080  
  selector:
    app: {{ .Values.prefix }}-bsf
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.prefix }}-bsf-gw
spec:
  selector:
    istio: ingressgateway 
  servers:
  - port:
      number: 80
      name: http2
      protocol: HTTP2
    hosts:
    - bsf.{{ .Values.istio_domain }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.prefix }}-bsf-vs
spec:
  hosts:
  - bsf.{{ .Values.istio_domain }}
  gateways:
  - {{ .Values.prefix }}-bsf-gw
  http:
  - match:
    - uri:
        prefix: /  
    route:
    - destination:
        host: {{ .Values.prefix }}-bsf
        port:
          number: 8080  