apiVersion: v1
data:
  gnodeb.yaml: |
    mcc: '{{ .Values.mcc }}'
    mnc: '{{ .Values.mnc }}'

    nci: '0x000000010'
    idLength: 32
    tac: '{{ .Values.tac }}'

    linkIp: 0.0.0.0
    ngapIp: 0.0.0.0
    gtpIp: 0.0.0.0

    # List of AMF address information
    amfConfigs:
      - address: {{ .Values.prefix }}-amf  
        port: 38412

    # List of supported S-NSSAIs by this gNB
    slices:
      - sst: 1

    # Indicates whether or not SCTP stream number errors should be ignored.
    ignoreStreamIds: true
kind: ConfigMap
metadata:
  name: {{ .Values.prefix }}-gnodeb