apiVersion: v1
data:
  nrf.yaml: |
    logger:
      file: /var/log/open5gs/nrf.log

    global:
      max:
        ue: 1024  # The number of UE can be increased depending on memory size.

    nrf:
      serving:  # 5G roaming requires PLMN in NRF
        - plmn_id:
            mcc: {{ .Values.mcc }}
            mnc: {{ .Values.mnc }}
      sbi:
        server:
          - address: 0.0.0.0
            port: 8080

kind: ConfigMap
metadata:
  name: {{ .Values.prefix }}-nrf
  

