apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prefix }}-nssf
  labels:
    app: {{ .Values.prefix }}-nssf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.prefix }}-nssf
  template:
    metadata:
      labels:
        app: {{ .Values.prefix }}-nssf
      annotations:
        sidecar.istio.io/inject: "{{ .Values.istio_enabled }}"        
    spec:
      securityContext:
        runAsUser: 1024
        runAsGroup: 1024
        fsGroup: 1024    
      imagePullSecrets:
      - name: {{ .Values.registry_secret }}
      initContainers:
      - name: wait-scp
        image: {{ .Values.registry_url }}/{{ .Values.init_image_name }}  
        command:
           - "/opt/wait_scp.sh" 
        env: 
          - name: PREFIX
            value: {{ .Values.prefix }}               
      containers:
      - name: {{ .Values.prefix }}-nssf
        image: {{ .Values.registry_url }}/{{ .Values.open5gs_image_name }}
        env:
          - name: NETYPE
            value: nssf   
          - name: PREFIX
            value: {{ .Values.prefix }}               
        command:
           - "/opt/start_app.sh"
        volumeMounts:
            - name: {{ .Values.prefix }}
              mountPath: /opt/open5gs/config/
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10   
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3          
      volumes:
        - name: {{ .Values.prefix }}
          configMap:
            name: {{ .Values.prefix }}-nssf
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.prefix }}-nssf
  name: {{ .Values.prefix }}-nssf
spec:
  ports:
  - port: 8080
    name: sbi
    protocol: TCP
    targetPort: 8080  
  selector:
    app: {{ .Values.prefix }}-nssf
  sessionAffinity: None
  type: ClusterIP            

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.prefix }}-nssf-gw
spec:
  selector:
    istio: ingressgateway 
  servers:
  - port:
      number: 8080
      name: http2
      protocol: HTTP2
    hosts:
    - nss.{{ .Values.istio_domain }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.prefix }}-nssf-vs
spec:
  hosts:
  - nss.{{ .Values.istio_domain }}
  gateways:
  - {{ .Values.prefix }}-nssf-gw
  http:
  - match:
    - uri:
        prefix: /  
    route:
    - destination:
        host: {{ .Values.prefix }}-nssf
        port:
          number: 8080      