apiVersion: v1
data:
  nssf.yaml: |
    logger:
      file: /var/log/open5gs/nssf.log

    global:
      max:
        ue: 1024  # The number of UE can be increased depending on memory size.

    nssf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 8080
        client:
          scp:
            - uri: http://{{ .Values.prefix }}-scp:8080
          nsi:
            - uri: http://{{ .Values.prefix }}-nrf:8080
              s_nssai:
                sst: 1
                
kind: ConfigMap
metadata:
  name: {{ .Values.prefix }}-nssf    
