apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prefix }}-pcf
  labels:
    app: {{ .Values.prefix }}-pcf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.prefix }}-pcf

  #serviceName: {{ .Values.prefix }}-pcf
  #podManagementPolicy: OrderedReady

  template:
    metadata:
      labels:
        app: {{ .Values.prefix }}-pcf
      annotations:
        sidecar.istio.io/inject: "{{ .Values.istio_enabled }}"        
    spec:
      securityContext:
        runAsUser: 1024
        runAsGroup: 1024
        fsGroup: 1024    
      imagePullSecrets:
      - name: {{ .Values.registry_secret }}
      initContainers:
      - name: wait-scp
        image: {{ .Values.registry_url }}/{{ .Values.init_image_name }}:{{ .Values.image_tag }}  
        env:
          - name: NETYPE
            value: pcf  
          - name: PREFIX
            value: {{ .Values.prefix }}          
        command:
           - "/opt/wait_scp.sh" 
        env: 
          - name: PREFIX
            value: {{ .Values.prefix }}              
      - name: wait-mongodb
        image: {{ .Values.registry_url }}/{{ .Values.init_image_name }}:{{ .Values.image_tag }}  
        command:
           - "/opt/wait_mongodb.sh"      
        env:
          - name: NETYPE
            value: pcf  
          - name: PREFIX
            value: {{ .Values.prefix }}                        
      containers:
      - name: {{ .Values.prefix }}-pcf
        image: {{ .Values.registry_url }}/{{ .Values.open5gs_image_name }}:{{ .Values.image_tag }}
        env:
          - name: NETYPE
            value: pcf  
          - name: PREFIX
            value: {{ .Values.prefix }}               
        command:
           - "/opt/start_app.sh"
        volumeMounts:
            - name: {{ .Values.prefix }}
              mountPath: /opt/open5gs/config/

        ports:
        - containerPort: 8080

        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10   

        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3  
                  
      volumes:
        - name: {{ .Values.prefix }}
          configMap:
            name: {{ .Values.prefix }}-pcf
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.prefix }}-pcf
  name: {{ .Values.prefix }}-pcf
spec:
  ports:
  - port: 8080
    name: http2
    protocol: TCP
    targetPort: 8080  
  - port: 9090
    name: metrics
    protocol: TCP
    targetPort: 9090     
  selector:
    app: {{ .Values.prefix }}-pcf
  sessionAffinity: None
  type: ClusterIP            

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.prefix }}-pcf-gw
spec:
  selector:
    istio: ingressgateway 
  servers:
  - port:
      number: 80
      name: http2
      protocol: HTTP2
    hosts:
    - pcf.{{ .Values.istio_domain }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.prefix }}-pcf-vs
spec:
  hosts:
  - pcf.{{ .Values.istio_domain }}
  gateways:
  - {{ .Values.prefix }}-pcf-gw
  http:
  - match:
    - uri:
        prefix: /  
    route:
    - destination:
        host: {{ .Values.prefix }}-pcf
        port:
          number: 8080    