apiVersion: v1
data:
  pcf.yaml: |
    db_uri: mongodb://{{ .Values.prefix }}-mongodb/open5gs
    logger:
      file: /var/log/open5gs/pcf.log

    global:
      max:
        ue: 1024  # The number of UE can be increased depending on memory size.

    pcf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 8080
        client:
          scp:
            - uri: http://{{ .Values.prefix }}-scp:8080
      metrics:
        server:
          - address: 0.0.0.0
            port: 9090

kind: ConfigMap
metadata:
  name: {{ .Values.prefix }}-pcf    
