apiVersion: v1
data:
  scp.yaml: |
    db_uri: mongodb://{{ .Values.prefix }}-mongodb/open5gs
    logger:
        file: /var/log/open5gs/scp.log
    sbi:
        server:
          no_tls: true
          cacert: /etc/open5gs/tls/ca.crt
          key: /etc/open5gs/tls/scp.key
          cert: /etc/open5gs/tls/scp.crt
        client:
          no_tls: true
          cacert: /etc/open5gs/tls/ca.crt
          key: /etc/open5gs/tls/scp.key
          cert: /etc/open5gs/tls/scp.crt
    scp:
        sbi:
          - addr: 0.0.0.0
            port: 8080
    nrf:
        sbi:
          - addr:
              - {{ .Values.prefix }}-nrf
            port: 8080
    parameter:
    max:
    time:
kind: ConfigMap
metadata:
  name: {{ .Values.prefix }}-scp

