apiVersion: v1
data:
  scp.yaml: |
    logger:
      file: /var/log/open5gs/scp.log

    global:
      max:
        ue: 1024  # The number of UE can be increased depending on memory size.

    scp:
      sbi:
        server:
          - address: 0.0.0.0
            port: 8080
        client:
          nrf:
            - uri: http://{{ .Values.prefix }}-nrf:8080

kind: ConfigMap
metadata:
  name: {{ .Values.prefix }}-scp

