apiVersion: v1
data:
  smf.yaml: |
    logger:
      file: /var/log/open5gs/smf.log

    global:
      max:
        ue: 1024  # The number of UE can be increased depending on memory size.

    smf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 8080
        client:
          scp:
            - uri: http://{{ .Values.prefix }}-scp:8080
      pfcp:
        server:
          - address: 0.0.0.0
        client:
          upf:
            - address: {{ .Values.prefix }}-upf
      gtpc:
        server:
          - address: 0.0.0.0
      gtpu:
        server:
          - address: 0.0.0.0
      metrics:
        server:
          - address: 0.0.0.0
            port: 9090
      session:
        - subnet: {{ .Values.upf_ip }}/{{ .Values.upf_mask }}

      dns:
        - 8.8.8.8
        - 8.8.4.4

      mtu: 1400
      freeDiameter: /etc/freeDiameter/smf.conf



kind: ConfigMap
metadata:
  name: {{ .Values.prefix }}-smf    
