apiVersion: v1
data:
  smf.yaml: |
    logger:
        file: /var/log/open5gs/smf.log
    sbi:
        server:
          no_tls: true
          cacert: /etc/open5gs/tls/ca.crt
          key: /etc/open5gs/tls/smf.key
          cert: /etc/open5gs/tls/smf.crt
        client:
          no_tls: true
          cacert: /etc/open5gs/tls/ca.crt
          key: /etc/open5gs/tls/smf.key
          cert: /etc/open5gs/tls/smf.crt
    smf:
        sbi:
          - addr: 0.0.0.0
            port: 8080
        pfcp:
          - addr: 0.0.0.0
        gtpc:
          - addr:  0.0.0.0
        gtpu:
          - addr:  0.0.0.0
        subnet:
          - addr: 10.45.0.1/16
            dnn: internet
        dns:
          - 8.8.8.8
          - 8.8.4.4
          
        mtu: 1400
        freeDiameter: /etc/freeDiameter/smf.conf
    scp:
        sbi:
          - addr: {{ .Values.prefix }}-scp
            port: 8080
    upf:
        pfcp:
          - addr: {{ .Values.prefix }}-upf
            dnn: [internet]
    parameter:
    max:
    pool:
    time:
kind: ConfigMap
metadata:
  name: {{ .Values.prefix }}-smf    
