apiVersion: v1
data:
  subscribers.yaml: |
{{ .Values.subscribers | toYaml | indent 4 }}


  subscriber.yaml: |
    # IMSI number of the subscriber. IMSI = [MCC|MNC|MSISDN] (In total 15 digits)
    supi: 'imsi-{{ .Values.subscriber.imsi }}'

    # Mobile Country Code value of HPLMN
    mcc: '{{ .Values.mcc }}'

    # Mobile Network Code value of HPLMN (2 or 3 digits)
    mnc: '{{ .Values.mnc }}'

    # Permanent subscription key
    key: '{{ .Values.subscriber.key }}'

    # Operator code (OP or OPC) of the UE
    op: '{{ .Values.subscriber.op }}'

    # This value specifies the OP type and it can be either 'OP' or 'OPC'
    opType: 'OPC'

    # Authentication Management Field (AMF) value
    amf: '{{ .Values.subscriber.amf }}'

    # IMEI number of the device. It is used if no SUPI is provided
    imei: '{{ .Values.subscriber.imei }}'

    # IMEISV number of the device. It is used if no SUPI and IMEI is provided
    imeiSv: '{{ .Values.subscriber.imeisv }}'

    # List of gNB IP addresses for Radio Link Simulation
    gnbSearchList:
      - "#GNODEB_IP#"

    # UAC Access Identities Configuration
    uacAic:
      mps: false
      mcs: false

    # UAC Access Control Class
    uacAcc:
      normalClass: 0
      class11: false
      class12: false
      class13: false
      class14: false
      class15: false

    # Initial PDU sessions to be established
    sessions:
      - type: 'IPv4'
        apn: 'internet'
        slice:
          sst: 1

    # Configured NSSAI for this UE by HPLMN
    configured-nssai:
      - sst: 1

    # Default Configured NSSAI for this UE
    default-nssai:
      - sst: 1
        sd: 1

    # Supported encryption algorithms by this UE
    integrity:
      IA1: true
      IA2: true
      IA3: true

    # Supported integrity algorithms by this UE
    ciphering:
      EA1: true
      EA2: true
      EA3: true

    # Integrity protection maximum data rate for user plane
    integrityMaxRate:
      uplink: 'full'
      downlink: 'full'

kind: ConfigMap
metadata:
  name: {{ .Values.prefix }}-subscriber