apiVersion: v1
data:
  udr.yaml: |
    db_uri: mongodb://{{ .Values.prefix }}-mongodb/open5gs
    logger:
      file: /var/log/open5gs/udr.log

    global:
      max:
        ue: 1024  # The number of UE can be increased depending on memory size.

    udr:
      sbi:
        server:
          - address: 0.0.0.0
            port: 8080
        client:
          scp:
            - uri: http://{{ .Values.prefix }}-scp:8080

kind: ConfigMap
metadata:
  name: {{ .Values.prefix }}-udr
