apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.prefix }}-upf
  labels:
    app: {{ .Values.prefix }}-upf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.prefix }}-upf
  serviceName: {{ .Values.prefix }}-upf
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: {{ .Values.prefix }}-upf
      annotations:
        sidecar.istio.io/inject: "{{ .Values.istio_enabled }}"      
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0          
      imagePullSecrets:
      - name: {{ .Values.registry_secret }}
      containers:
      - name: {{ .Values.prefix }}-upf
        image: {{ .Values.registry_url }}/{{ .Values.open5gs_image_name }}:{{ .Values.image_tag }}              
        securityContext:
          privileged: true
          capabilities:
            add: ["NET_ADMIN", "SYS_TIME"]   
        env:
          - name: DEBUG
            value: upf          
          - name: NETYPE
            value: upf  
          - name: PREFIX
            value: {{ .Values.prefix }}                
        command:
           - "/opt/start_app.sh"                 
        volumeMounts:
            - name: open5gs
              mountPath: /opt/open5gs/config/
            - name: dev-tun
              mountPath: /dev/net/tun                   
        ports:
        - containerPort: 2152
        - containerPort: 8805
        - containerPort: 9090        
      volumes:
        - name: {{ .Values.prefix }}
          configMap:
            name: {{ .Values.prefix }}-upf
        - name: dev-tun            
          hostPath:
            path: /dev/net/tun
            type: CharDevice 
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.prefix }}-upf
  name: {{ .Values.prefix }}-upf
spec:
  ports:
  - port: 2152    
    protocol: UDP
    name: upf1
    targetPort: 2152
  - port: 8805
    protocol: UDP
    targetPort: 8805
    name: upf2
  - port: 9090
    protocol: TCP
    targetPort: 9090
    name: upf3   
  selector:
    app: {{ .Values.prefix }}-upf
  sessionAffinity: None
  type: ClusterIP

