apiVersion: v1
data:
  upf.yaml: |
    logger:
      file: /var/log/open5gs/upf.log

    global:
      max:
        ue: 1024  # The number of UE can be increased depending on memory size.

    upf:
      pfcp:
        server:
          - address: 0.0.0.0
        client:
      gtpu:
        server:
          - address: 0.0.0.0
      session:
        - subnet: {{ .Values.upf_ip }}/{{ .Values.upf_mask }}
      metrics:
        server:
          - address: 0.0.0.0
            port: 9090

kind: ConfigMap
metadata:
  name: {{ .Values.prefix }}-upf