apiVersion: v1
data:
  upf.yaml: |
    logger:
        file: /var/log/open5gs/upf.log
    upf:
        pfcp:
          - addr: 0.0.0.0
        gtpu:
          - addr: 0.0.0.0
        subnet:
          - addr: 10.45.0.1/16      
        metrics:
          - addr: 0.0.0.0
            port: 9090
    smf:
    parameter:
    max:
    time:
kind: ConfigMap
metadata:
  name: {{ .Values.prefix }}-upf