export OPEN5GS_IMAGE_NAME="open5gs"
export UERAMSIM_IMAGE_NAME="ueramsim"
export INIT_IMAGE_NAME="init"
export IMAGE_TAG="0.0.3"
export REGISTRY_URL="registry.kube.int"
export PROJECT="open5gs"
export NAMESPACE="open5gs"
export REGISTRY_SECRET_NAME="open5gs-secret"
export PREFIX="open5gs"
export MCC="724"
export MNC="17"
export NCI="0x000000010"
export TAC="100"
export SMF_SUBNET="10.45.0.1/16"
export DNS_SERVER_1="8.8.8.8"
export DNS_SERVER_2="8.8.4.4"

